config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :comparisons
  resources :customers, only: [:index]
  resources :documents
  get 'documents/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
end

app/models/comparison.rb
class Comparison < ApplicationRecord
  attr_reader :exit_status_msg
  has_many :documents
  accepts_nested_attributes_for :documents, allow_destroy: true
  
  
  def documents_dir
    return Rails.root.join('public', 'images', 'comparisons', "#{id}") if Rails.env == 'development'
    File.join('/var', 'www', 'fpa', 'shared', 'public', 'images', 'comparisons', "#{id}")
  end
  
  def result_image_path
    File.join(documents_dir, 'comparison_output.png')
  end
  
  def result_image_url
    "comparisons/#{id}/comparison_output.png"
  end
  
  
  def run
    
    unless self.documents.size == 2
      @exit_status_msg = "The must be 2 files to compare, no more, mo less. Received #{self.documents.size}"
      return false
    end
    
    puts "\n\npdf1 #{self.documents.first.file.path}"
    puts "pdf2 #{self.documents.last.file.path} \n\n"
    
    source_virtualenv_path
    if $?.exitstatus > 0
      raise "I failed to activate python env. #{$?.exitstatus} \n virtualenv_path: #{virtualenv_path}"
      return false 
    end
    
    system "mkdir #{documents_dir}"
    if $?.exitstatus > 0
      @exit_status_msg = "I failed to create #{documents_dir}, I am very sorry :'( #{$?.exitstatus}"
      raise @exit_status_msg
      return false 
    end
    
    system "cd vendor/utils/pdf-diff; pdf-diff #{self.documents.first.file.path} #{self.documents.last.file.path} > #{result_image_path}"
    if $?.exitstatus > 0
      @exit_status_msg = "I failed to switch directories, I am very sorry :'( #{$?.exitstatus}"
      raise @exit_status_msg
      return false 
    end

    true
  end
  
  
  private
  
    def source_virtualenv_path
      return (system "source ~/.virtualenvs/fpa/bin/activate") if Rails.env == 'development'
      source_env_from('/home/deploy/fpa/fpaenv/bin/activate')
    end
  
    def virtualenv_path
      return '~/.virtualenvs/fpa/bin/activate' if Rails.env == 'development'
      '~/fpa/fpaenv/bin/activate'
    end
    
    # Read in the bash environment, after an optional command.
    #   Returns Array of key/value pairs.
    def bash_env(cmd=nil)
      env = `#{cmd + ';' if cmd} printenv`
      env.split(/\n/).map {|l| l.split(/=/)}
    end

    # Source a given file, and compare environment before and after.
    #   Returns Hash of any keys that have changed.
    def bash_source(file)
      Hash[ bash_env(". #{File.realpath file}") - bash_env() ]
    end

    # Find variables changed as a result of sourcing the given file, 
    #   and update in ENV.
    def source_env_from(file)
      bash_source(file).each {|k,v| ENV[k] = v }
    end
  
end

app/controllers/comparisons_controller.rb
class ComparisonsController < ApplicationController
  before_action :set_comparison, only: [:show, :update, :destroy]

  # GET /comparisons
  # GET /comparisons.json
  def index
    @comparisons = Comparison.all
  end
  
  def new
    @comparison = Comparison.new
    2.times { @comparison.documents.build }
  end

  # GET /comparisons/1
  # GET /comparisons/1.json
  def show
  end

  # POST /comparisons
  # POST /comparisons.json
  def create
    @comparison = Comparison.new(comparison_params)

    if @comparison.save && @comparison.run
      flash[:success] = @comparison.exit_status_msg
      redirect_to @comparison
    else
      flash[:error] = @comparison.errors.methods
      render 'new'
    end
  end

  # PATCH/PUT /comparisons/1
  # PATCH/PUT /comparisons/1.json
  def update
    if @comparison.update(comparison_params) && @comparison.run
      redirect_to @comparison
    else
      render json: @comparison.errors, status: :unprocessable_entity
    end
  end

  # DELETE /comparisons/1
  # DELETE /comparisons/1.json
  def destroy
    @comparison.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comparison
      @comparison = Comparison.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comparison_params
      params.require(:comparison).permit(:description, documents_attributes: [:file, :id])
    end
end

app/views/comparisons/_form.html.erb
<!-- app/views/comparisons/_form.html.erb -->
<%= form_for @comparison, html: { class: 'dropzone-form', multipart: true } do |f| %>
  
  <fieldset class="dropzone" style="margin-top:3em;padding:2em;">
    <div class="form-group">
      <%= f.fields_for :documents do |document_fields| %>
        <%= f.label :document, "PDF Document #{document_fields.index+1}", class: 'col-form-label' %>
        <div class="curved-dashed-border form-group text-center">
          <br>
          <%= document_fields.file_field :file %>
          <div class="dz-default dz-message">
            <span><small id="description-help" class="form-text text-muted">Or dropping file here works also.</small></span>
          </div>
        </div>
      <% end %>
    </div>
    
    
    <div class="form-group">
      <%= f.label :description, class: 'col-form-label' %>
      <div class="stacked">
        <%= f.text_area :description, class: 'form-control text-field' %>
      </div>
      <small id="description-help" class="form-text text-muted">This is optional.</small>
    </div>

    <div class="form-group">
      <div class="actions">
        <%= f.submit "Show Difference", class: 'btn btn-primary' %>
        <%= link_to 'Cancel', comparisons_path, class: 'btn btn-mini' %>
      </div>
    </div>
  </fieldset>
 
<% end %>

app/views/comparisons/new.html.erb
<div class="container">
  <h1 id="upload_pdf_documents" class="text-center">
    Upload PDF Documents
  </h1>

  <div class="form-container">
    <%= render partial: "form" %>
  </div>
</div>

app/views/comparisons/show.html.erb
<div class="row">
  <section>
      <div class="col-lg-8 col-lg-offset-2">

        <h1 id="side-by-side-comparison" class="text-center">Side By Side Comparison</h1>
        <div class="centered-image">
          <span></span>
          <%= image_tag(@comparison.result_image_url, title: "Comparison results.", class: "xy-centered", skip_pipeline: true) %>
        </div>
      </div>
  </section>
</div>

    