config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :comparisons
  resources :customers, only: [:index]
  resources :documents
  get 'documents/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Presidio Strategic Communications - Utilities" %></title>
    <%= csrf_meta_tags %>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Utilities" %>">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Berkshire+Swash|Hind+Vadodara|Krona+One" rel="stylesheet">
    <%= favicon_link_tag %>
  </head>

  <body>
    <div class="container-fluid">
      <div class="row d-flex d-md-block flex-nowrap wrapper">
           
        <div class="col-md-3 float-left col-1 pl-0 pr-0 collapse width show" id="sidebar">
          <div class="list-group border-0 card text-center text-md-left">
            <%= sidebar_link_to company_name, root_url %>
            <%= sidebar_link_to current_user_email, root_url %>
            <%= sidebar_link_to sidebar_slack_icon, "https://presidiosc.slack.com" %>
            
            <!-- Documents Menu -->
            <a href="#menu3" class="list-group-item d-inline-block collapsed" data-toggle="collapse" data-parent="#sidebar" aria-expanded="false">
              <i class="fa fa-book"></i>
              <span class="hidden-sm-down">Documents</span>
            </a>
            <div class="collapse" id="menu3">
              <a href="#menu3sub2" class="list-group-item" data-toggle="collapse" aria-expanded="false">Utilities</a>
              <div class="collapse" id="menu3sub2">
                <%= link_to "PDF Diff Tool", new_comparison_url, class: 'list-group-item', data: { parent: '#menu3sub2' } %>
              </div>
            </div>
            <!-- End Documents Menu -->
            
            <%= sidebar_link_to sidebar_media_icon, '#' %>
            <%= sidebar_link_to sidebar_calendar_icon, '#' %>
            <%= sidebar_link_to sidebar_email_icon, '#' %>
            <%= sidebar_link_to sidebar_reports_icon, '#' %>
            
            <!-- Settings Menu -->
            <a href="#menu1" class="list-group-item d-inline-block collapsed" data-parent="#sidebar" data-toggle="collapse" aria-expanded="false">
              <i class="fa fa-gear"></i> <span class="hidden-sm-down">Settings</span>
            </a>
            <div class="collapse" id="menu1">
              <a href="#menu1sub1" class="list-group-item" data-toggle="collapse" aria-expanded="false">Subitem 1 </a>
                <div class="collapse" id="menu1sub1">
                  <a href="#" class="list-group-item" data-parent="#menu1sub1">Subitem 1 a</a>
                  <a href="#" class="list-group-item" data-parent="#menu1sub1">Subitem 2 b</a>
                  <a href="#menu1sub1sub1" class="list-group-item" data-toggle="collapse" aria-expanded="false">Subitem 3 c </a>
                  <div class="collapse" id="menu1sub1sub1">
                    <a href="#" class="list-group-item" data-parent="#menu1sub1sub1">Subitem 3 c.1</a>
                    <a href="#" class="list-group-item" data-parent="#menu1sub1sub1">Subitem 3 c.2</a>
                  </div>
                  <a href="#" class="list-group-item" data-parent="#menu1sub1">Subitem 4 d</a>
                  <a href="#menu1sub1sub2" class="list-group-item" data-toggle="collapse" aria-expanded="false">Subitem 5 e </a>
                  <div class="collapse" id="menu1sub1sub2">
                    <a href="#" class="list-group-item" data-parent="#menu1sub1sub2">Subitem 5 e.1</a>
                    <a href="#" class="list-group-item" data-parent="#menu1sub1sub2">Subitem 5 e.2</a>
                  </div>
                </div>
                <a href="#" class="list-group-item" data-parent="#menu1">Subitem 2</a>
                <a href="#" class="list-group-item" data-parent="#menu1">Subitem 3</a>
            </div>
            <!-- End Settings Menu -->
            
            <%= sidebar_link_to sidebar_strongbox_icon, customers_path %>
            <%= sidebar_link_to_logout %>
          </div>
        </div>
        
        <main id="main" class="col-md-9 float-left col px-5 pl-md-2 pt-2 main">
          <a href="#" data-target="#sidebar" data-toggle="collapse"><i class="fa fa-navicon fa-2x py-2 p-1"></i></a>
          <% if notice.present? %>
            <aside class="alert alert-info">
              <%= notice %>
            </aside>
          <% end %>
          
          <% if alert.present? %>
            <aside class="alert alert-danger">
              <%= alert %>
            </aside>
          <% end %>
          
          
          <%= yield %>
        </main>
      </div>        
    </div>
  </body>
</html>